"""empty message

Revision ID: 11c08d782e23
Revises: 38bc52f58570
Create Date: 2020-05-12 21:11:51.559203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c08d782e23'
down_revision = '38bc52f58570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_swap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labtechID', sa.String(length=10), nullable=True),
    sa.Column('timeslotID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labtechID'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['timeslotID'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_swap')
    # ### end Alembic commands ###
