"""empty message

Revision ID: 11e54834675e
Revises: 11c08d782e23
Create Date: 2020-05-17 01:19:33.676314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e54834675e'
down_revision = '11c08d782e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labtechs', sa.Column('hours_worked', sa.Integer(), nullable=False))
    op.drop_column('labtechs', 'hoursWorked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labtechs', sa.Column('hoursWorked', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('labtechs', 'hours_worked')
    # ### end Alembic commands ###
