"""empty message

Revision ID: 38bc52f58570
Revises: 
Create Date: 2020-05-11 23:20:07.438470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bc52f58570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labtechs',
    sa.Column('uwiIssuedID', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=False),
    sa.Column('lastname', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('hoursWorked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uwiIssuedID')
    )
    op.create_table('users',
    sa.Column('uwiIssuedID', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=False),
    sa.Column('lastname', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uwiIssuedID')
    )
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DENIED', 'CONFIRM', 'APPROVED', name='status'), nullable=False),
    sa.Column('infoType', sa.Enum('FIRSTNAME', 'LASTNAME', 'PASSWORD', 'ID', name='infotype'), nullable=False),
    sa.Column('newInfo', sa.String(length=120), nullable=True),
    sa.Column('labtech_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['labtech_id'], ['labtechs.uwiIssuedID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clock_in_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labtech_id', sa.String(length=10), nullable=True),
    sa.Column('timeslot_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['labtech_id'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labtech_timeslot',
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('labtech_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['labtech_id'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('timeslot_id', 'labtech_id')
    )
    op.create_table('swap_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DENIED', 'CONFIRM', 'APPROVED', name='status'), nullable=False),
    sa.Column('labtech_request_id', sa.String(length=10), nullable=True),
    sa.Column('labtech_confirm_id', sa.String(length=10), nullable=True),
    sa.Column('admin_approve_id', sa.String(length=10), nullable=True),
    sa.Column('request_labtech_timeslot_id', sa.Integer(), nullable=True),
    sa.Column('confirm_labtech_timeslot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_approve_id'], ['users.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['confirm_labtech_timeslot_id'], ['timeslots.id'], ),
    sa.ForeignKeyConstraint(['labtech_confirm_id'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['labtech_request_id'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['request_labtech_timeslot_id'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_request')
    op.drop_table('labtech_timeslot')
    op.drop_table('clock_in_entry')
    op.drop_table('user_request')
    op.drop_table('timeslots')
    op.drop_table('users')
    op.drop_table('labtechs')
    op.drop_table('events')
    # ### end Alembic commands ###
