"""empty message

Revision ID: 45f94f561fdb
Revises: ffa7a3c3379b
Create Date: 2020-05-10 22:04:20.920946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f94f561fdb'
down_revision = 'ffa7a3c3379b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swap_request', sa.Column('labtech_confirm_id', sa.Integer(), nullable=True))
    op.add_column('swap_request', sa.Column('labtech_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'swap_request', 'labtechs', ['labtech_confirm_id'], ['uwiIssuedID'])
    op.create_foreign_key(None, 'swap_request', 'labtechs', ['labtech_request_id'], ['uwiIssuedID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swap_request', type_='foreignkey')
    op.drop_constraint(None, 'swap_request', type_='foreignkey')
    op.drop_column('swap_request', 'labtech_request_id')
    op.drop_column('swap_request', 'labtech_confirm_id')
    # ### end Alembic commands ###
