"""empty message

Revision ID: 4bdd5579d382
Revises: 8022ec8b7995
Create Date: 2020-05-10 21:04:24.005967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdd5579d382'
down_revision = '8022ec8b7995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DENIED', 'CONFIRM', 'APPROVED', name='status'), nullable=True),
    sa.Column('labtech_request_id', sa.Integer(), nullable=True),
    sa.Column('labtech_confirm_id', sa.Integer(), nullable=True),
    sa.Column('admin_approve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_approve_id'], ['users.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['labtech_confirm_id'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['labtech_request_id'], ['labtechs.uwiIssuedID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_request')
    # ### end Alembic commands ###
