"""empty message

Revision ID: 8022ec8b7995
Revises: 
Create Date: 2020-05-09 21:25:41.863467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8022ec8b7995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labtechs',
    sa.Column('uwiIssuedID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=False),
    sa.Column('lastname', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('hoursWorked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uwiIssuedID')
    )
    op.create_table('users',
    sa.Column('uwiIssuedID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.String(length=35), nullable=False),
    sa.Column('lastname', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uwiIssuedID')
    )
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labtech_timeslot',
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('labtech_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['labtech_id'], ['labtechs.uwiIssuedID'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.id'], ),
    sa.PrimaryKeyConstraint('timeslot_id', 'labtech_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labtech_timeslot')
    op.drop_table('timeslots')
    op.drop_table('users')
    op.drop_table('labtechs')
    op.drop_table('events')
    # ### end Alembic commands ###
