"""empty message

Revision ID: f60da52a3e37
Revises: 45f94f561fdb
Create Date: 2020-05-10 23:11:49.502746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60da52a3e37'
down_revision = '45f94f561fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swap_request', sa.Column('confirm_labtech_timeslot_id', sa.Integer(), nullable=True))
    op.add_column('swap_request', sa.Column('request_labtech_timeslot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'swap_request', 'timeslots', ['request_labtech_timeslot_id'], ['id'])
    op.create_foreign_key(None, 'swap_request', 'timeslots', ['confirm_labtech_timeslot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'swap_request', type_='foreignkey')
    op.drop_constraint(None, 'swap_request', type_='foreignkey')
    op.drop_column('swap_request', 'request_labtech_timeslot_id')
    op.drop_column('swap_request', 'confirm_labtech_timeslot_id')
    # ### end Alembic commands ###
